version: "3.9"

services:
  blog-backend:
    build: ./backend
    container_name: blog-backend
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb+srv://2MD:Atlas2md93@cluster0.lwup07w.mongodb.net/blog?retryWrites=true&w=majority
    ports:
      - "3001:3001"

  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:3001/api/v1
    container_name: blog-frontend
    ports:
      - "3000:80"
    depends_on:
      - blog-backend
