version: "3.9"

services:
  blog-backend:
    build: ./backend
    container_name: blog-backend
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"

  blog-frontend:
    build:
      context: .
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: blog-frontend
    ports:
      - "3000:80"
    depends_on:
      - blog-backend